#!/usr/bin/env python3
"""Boot persistence.

Anneal did not survive a machine reboot. Nothing had ever started it at boot —
there was no launchd job at all — so after a restart the tailnet URL was still
up (that configuration lives in Tailscale's own state and survives on its own)
and proxying to a dead port. From outside, indistinguishable from a crash.

These are structural checks on the launcher scripts and the generated plist.
The parts that need a real machine — that it actually comes back after a
reboot, and that it waits out a late-mounting external disk — are verified by
rebooting, and no test here should be mistaken for having done that.
"""

import os
import plistlib
import re
import subprocess
import unittest

from tests.context import REPO_ROOT

SERVICE = os.path.join(REPO_ROOT, "service.sh")
BOOT = os.path.join(REPO_ROOT, "boot.sh")


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


class TestTheScriptsParse(unittest.TestCase):
    """A shell script with a syntax error fails at boot, in a log nobody reads."""

    def test_every_launcher_is_valid_bash(self):
        for name in ("boot.sh", "start-api.sh", "stop-api.sh", "service.sh"):
            path = os.path.join(REPO_ROOT, name)
            done = subprocess.run(["bash", "-n", path], capture_output=True, text=True)
            self.assertEqual(done.returncode, 0, "%s: %s" % (name, done.stderr))

    def test_they_are_executable(self):
        for name in ("boot.sh", "service.sh"):
            self.assertTrue(os.access(os.path.join(REPO_ROOT, name), os.X_OK), name)


class TestTheGeneratedPlist(unittest.TestCase):
    """Generated by running service.sh with HOME pointed at a temp directory, so
    this never touches the real LaunchAgents folder."""

    @classmethod
    def setUpClass(cls):
        import tempfile
        cls.home = tempfile.mkdtemp()
        # `plist`, never `install`. install calls launchctl bootstrap, and an
        # earlier version of this test did exactly that — registering a real
        # LaunchAgent on the machine running the suite, pointing at a plist in a
        # temp directory that was then deleted. A test must not install things.
        subprocess.run([SERVICE, "plist"], cwd=REPO_ROOT, capture_output=True,
                       text=True, env=dict(os.environ, HOME=cls.home))
        cls.path = os.path.join(cls.home, "Library", "LaunchAgents",
                                "com.anneal.gateway.plist")

    @classmethod
    def tearDownClass(cls):
        import shutil
        shutil.rmtree(cls.home, ignore_errors=True)

    def plist(self):
        if not os.path.isfile(self.path):
            self.skipTest("service.sh could not write a plist in this environment")
        with open(self.path, "rb") as fh:
            return plistlib.load(fh)

    def test_it_is_valid_plist_xml(self):
        self.plist()          # plistlib raises if it is not

    def test_it_runs_boot_not_start_api(self):
        """start-api.sh backgrounds the supervisor and exits, so launchd would
        see a clean exit on every launch and KeepAlive would restart it in a
        loop. boot.sh execs the supervisor so the supervised pid is the real one."""
        argv = self.plist()["ProgramArguments"]
        # argv[0] is the private bash that holds the Full Disk Access grant;
        # boot.sh is what it runs.
        self.assertTrue(argv[0].endswith("anneal-bash"), argv)
        self.assertTrue(argv[-1].endswith("boot.sh"), argv)
        self.assertFalse(any("start-api" in a for a in argv), argv)

    def test_it_runs_through_the_copy_that_holds_the_grant(self):
        """Running /bin/bash here would work only if /bin/bash itself had Full
        Disk Access, which is the broad grant this arrangement avoids."""
        argv = self.plist()["ProgramArguments"]
        self.assertNotEqual(argv[0], "/bin/bash", argv)

    def test_it_starts_at_load(self):
        self.assertTrue(self.plist()["RunAtLoad"])

    def test_it_restarts_on_crash_but_not_after_a_clean_stop(self):
        """The supervisor exits 0 on SIGTERM, so SuccessfulExit=false leaves a
        deliberate stop alone instead of fighting whoever ran stop-api.sh."""
        keep = self.plist()["KeepAlive"]
        self.assertIsInstance(keep, dict, "bare KeepAlive would resurrect a deliberate stop")
        self.assertFalse(keep["SuccessfulExit"])

    def test_it_throttles(self):
        """A machine whose external disk never mounts should not be hammered."""
        self.assertGreaterEqual(self.plist().get("ThrottleInterval", 0), 10)


class TestTheTestsDoNotInstallAnything(unittest.TestCase):
    """Guard on the guard. This suite generates a plist, and the difference
    between generating and installing is one word in a subprocess call."""

    def test_the_suite_never_calls_install(self):
        # The subcommands actually invoked, not the prose about them — an
        # earlier version of this matched its own comment.
        src = read(os.path.join(REPO_ROOT, "tests", "unit", "test_service.py"))
        called = set(re.findall(r'subprocess\.run\(\[SERVICE, "(\w[\w-]*)"', src))
        self.assertTrue(called, "expected at least one service.sh invocation")
        self.assertEqual(called - {"plist", "status"}, set(),
                         "tests may only run side-effect-free subcommands")

    def test_plist_mode_does_not_touch_launchctl(self):
        """`plist` exists precisely so the tests have a side-effect-free path."""
        src = read(SERVICE)
        body = src[src.index("\nplist)"):src.index("\nstatus)")]
        # Strip comments: the body explains that it does not call launchctl,
        # and an earlier version of this test matched that sentence.
        code = "\n".join(re.sub(r"#.*", "", ln) for ln in body.splitlines())
        self.assertNotIn("launchctl", code)


class TestTheGrantIsNarrow(unittest.TestCase):
    """A LaunchAgent cannot read an external volume at all — measured with a
    probe agent that could not even `ls` the directory. Boot persistence needs
    Full Disk Access, and *what* holds that grant is the security decision."""

    def setUp(self):
        self.src = read(SERVICE)

    def test_the_grant_goes_to_a_private_copy_not_system_bash(self):
        """Granting to /bin/bash would give full disk access to every shell
        script anything on the machine runs, including one piped from a URL."""
        self.assertIn("anneal-bash", self.src)
        self.assertNotIn("Full Disk Access to /bin/bash", self.src)

    def test_a_stale_copy_is_refreshed_rather_than_trusted(self):
        """An OS update changes /bin/bash; the copy still runs but no longer
        matches, and re-copying invalidates the grant. Better to say so than to
        discover it at the next reboot."""
        self.assertIn("cmp -s /bin/bash", self.src)

    def test_install_rules_out_a_missing_grant_before_bothering(self):
        self.assertRegex(self.src, r"if probably_denied; then\n\s+grant_instructions\n\s+exit 1")

    def test_access_is_tested_by_reading_the_volume_not_by_a_checkbox(self):
        self.assertRegex(self.src, r'probably_denied\(\) \{[^}]*ls ')

    def test_the_preflight_check_only_claims_to_rule_out(self):
        """Run from a terminal it inherits that terminal's disk access, so a
        pass says nothing about launchd — measured: it reported GRANTED while
        the real agent could not list the directory."""
        self.assertIn("probably_denied", self.src)
        self.assertNotIn("has_disk_access", self.src)

    def test_install_verifies_by_seeing_whether_the_job_actually_starts(self):
        """The only check that runs in launchd's context is launchd running it."""
        block = self.src[self.src.index("\ninstall)"):self.src.index("\nuninstall)")]
        self.assertIn("launchctl bootstrap", block)
        self.assertIn("/health", block)
        self.assertIn("grant_instructions", block)

    def test_install_stops_a_hand_started_gateway_first(self):
        """boot.sh exits 0 when the pidfile shows something running, so without
        this the post-install health check passes against the process that was
        already there — reporting success for a job that did nothing."""
        block = self.src[self.src.index("\ninstall)"):self.src.index("\nuninstall)")]
        self.assertIn("stop-api.sh", block)
        self.assertLess(block.index("stop-api.sh"), block.index("launchctl bootstrap"),
                        "it must stop the old one before starting the new one")

    def test_the_copied_shell_is_resigned(self):
        """Copying a signed system binary invalidates the signature and macOS
        SIGKILLs the copy before it runs a line."""
        self.assertRegex(self.src, r"codesign --force --sign -")

    def test_the_launchd_log_is_not_on_the_external_volume(self):
        """launchd opens StandardOutPath itself, before the job runs and before
        any grant applies to it. A path on the volume fails the spawn outright
        with EX_CONFIG and no diagnostic anywhere. Measured."""
        self.assertRegex(self.src, r'LOG_DIR="\$HOME')


class TestBootWaitsForTheVolume(unittest.TestCase):
    """The whole reason boot.sh exists separately from start-api.sh: launchd
    starts login items well before an external disk is mounted."""

    def setUp(self):
        self.src = read(BOOT)

    def test_it_waits_rather_than_failing_immediately(self):
        self.assertRegex(self.src, r"while \[\[ ! -d \"\$ROOT\" \]\]")

    def test_the_wait_is_bounded(self):
        self.assertIn("ANNEAL_BOOT_WAIT", self.src)
        self.assertRegex(self.src, r"giving up")

    def test_it_execs_the_supervisor(self):
        """Without exec, launchd watches a wrapper that exits immediately."""
        self.assertTrue(re.search(r"^exec .*supervisor\.py", self.src, re.M),
                        "boot.sh must exec the supervisor, not background it")

    def test_start_api_still_fails_fast_when_the_volume_is_missing(self):
        """Opposite behaviour on purpose: a human typed the command and wants to
        be told, rather than watching it hang for five minutes."""
        src = read(os.path.join(REPO_ROOT, "start-api.sh"))
        self.assertRegex(src, r"is the Storage SSD mounted")

    def test_exposure_is_still_opt_in_at_boot(self):
        """A boot path that ignored ANNEAL_EXPOSE would put a fresh clone on the
        tailnet without being asked."""
        self.assertIn("ANNEAL_EXPOSE", self.src)


class TestStopAndStartCooperateWithLaunchd(unittest.TestCase):
    def test_stop_unloads_the_job_before_killing_anything(self):
        """Otherwise KeepAlive restarts it and the stop lasts a second."""
        src = read(os.path.join(REPO_ROOT, "stop-api.sh"))
        self.assertIn("bootout", src)
        self.assertLess(src.index("bootout"), src.index("kill -9"),
                        "the job must be unloaded before the process is killed")

    def test_start_restores_the_job_it_unloaded(self):
        """Otherwise a stop/start cycle silently leaves the machine without the
        boot persistence it was configured to have — which is exactly the class
        of asymmetry that took the tailnet down once already."""
        src = read(os.path.join(REPO_ROOT, "start-api.sh"))
        self.assertIn("bootstrap", src)


if __name__ == "__main__":
    unittest.main()
